
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

print("Execution Started")
x2 = 2
x1 = 1
total = 0
while (x2<4000000):
    print(x2)
    if (x2%2==0):
        total+=x2
    x0=x1
    x1=x2
    x2=x2+x0
print(total)

